version: '2'

volumes:
  webroot:
  certificates:

services:

  api:
    build:
      context: ..
      dockerfile: deployment/api/Dockerfile
    image: todorus/politweetici:api
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:database

  db:
    image: postgres:9.6.2
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: deployment/nginx/Dockerfile.dev
    image: todorus/politweetici:api
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:api
    volumes:
      - webroot:/var/www
      - certificates:/certificates
