version: '2'
services:

  api:
    build:
      context: ..
      dockerfile: deployment/api/Dockerfile
    image: todorus/politweetici:api
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:database
    volumes:
      - ../app:/app

  db:
    image: postgres:9.6.2
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  web:
    build:
      context: ..
      dockerfile: deployment/nginx/Dockerfile.dev
    image: todorus/politweetici:api
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:api

  test:
    build:
      context: ..
      dockerfile: deployment/test/Dockerfile
    image: todorus/politweetici:test
    depends_on:
      - api
      - db
    links:
      - api:api
      - db:database
    volumes:
      - ../reports:/frame/results
    command: bash -c "sleep 10s; echo 'starting tests'; nose2 -c tests/nose2.cfg --junit-xml"
